# Config settings
title: AS-8X API Documentation
baseurl: "/as8x-docs"

# Search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [index.md, search.html]

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-html-pipeline

header_pages:
 - search.html
 - apiIndex.html

versions:
  - id: bank
    product: "ՀԾ-Բանկ"
    versions: ["1.0", "2.0"]
  - id: enterprise
    product: "ՀԾ-Ձեռնարկություն"
    versions: ["3.0", "3.1"]
  - id: wages
    product: "ՀԾ-Աշխատավարձ"
    versions: ["4.0", "4.1"]
